language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install

script:
  - composer test

sudo: false

cache:
  directories:
  - "$HOME/.composer/cache"
